spring:
  profiles:
    active: test
---
spring:
  profiles: development
  jpa:
    show-sql: false
    generate-ddl: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: 8323277
---

spring:
  profiles: test
  jpa:
    show-sql: false
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
