spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    show-sql: false
    generate-ddl: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

  datasource:

    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: 8323277
---

spring:
  profiles: test
  jpa:
    show-sql: false
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
