spring:
  profiles: production
  jpa:
    show-sql: false
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false


  datasource:

    url: jdbc:postgresql://${MOVIES_DB_HOST:localhost}:${MOVIES_DB_PORT:5432}/${MOVIES_DB:movies}
    username: ${MOVIES_DB_USER:movies}
    password: ${MOVIES_DB_PASSWORD:movies}


---
spring:
  profiles: staging
  jpa:
    show-sql: false
    generate-ddl: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update

  datasource:

    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: 8323277
---

spring:
  profiles: test
  jpa:
    show-sql: false
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
